  name: QuickShop
  main: main.jake.quickshop.QuickShop
  version: 1.2
  author: jlariv11
  description: Adds easy to use shops using items as currency
  api-version: 1.16

  commands:
    openshop:
      usage: /openshop
      description: opens the shop interface
      permission: quickshop.shop
      permission-message: You do not have permission to use this command.
    adminshop:
      usage: /adminshop
      description: opens the admin shop interface
      permission: quickshop.adminshop
      permission-message: You do not have permission to use this command.
    removeshop:
      usage: /removeshop
      description: opens the remove shop interface
      permission: quickshop.remove
      permission-message: You do not have permission to use this command.
    currency:
      usage: /currency info /currency set <item>
      description: changes the currency of the shops or lists the current currency
      permission: quickshop.setcurrency
      permission-message: You do not have permission to use this command.

    test:
      usage: /test
      description: opens the shop interface
      permission: simpleshop.test
      permission-message: You do not have permission to use this command.